// lab-04-frameworks/02-angular/angular-github-app/src/app/members/members-table/member-row.component.ts
import { Component, Input } from "@angular/core";
import { MemberEntity } from "../models/member.model";

@Component({
  selector: "[app-member-row]",
  templateUrl: "./member-row.component.html",
  styles: [],
})
export class MemberRowComponent {
  @Input() member: MemberEntity;
}

<!-- <ng-container>
  <tr>
    <td>
      <img [src]="member.avatar_url" style="max-width:10rem;" />
    </td>
    <td>
      <span>{{member.id}}</span>
    </td>
    <td>
      <span>{{member.login}}</span>
    </td>
  </tr>
</ng-container> -->

<td>
  <img [src]="member.avatar_url" style="max-width: 10rem;" />
</td>
<td>
  <span>{{ member.id }}</span>
</td>
<td>
  <span>{{ member.login }}</span>
</td>

// lab-04-frameworks/01-react/react-github-app/src/components/membersTable/memberRow.tsx
import * as React from "react";
import { MemberEntity } from "../../model/member";

export const MemberRow = (props: { member: MemberEntity }) => (
  <tr>
    <td>
      <img src={props.member.avatar_url} style={{ maxWidth: "10rem" }} />
    </td>
    <td>
      <span>{props.member.id}</span>
    </td>
    <td>
      <span>{props.member.login}</span>
    </td>
  </tr>
);
